services:
  
  django:
    build: .
    restart: always
    container_name: django
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    networks:
      - backend_{{ cookiecutter.project_slug }}

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/nginx/ssl/:ro
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
    networks:
      - backend_{{ cookiecutter.project_slug }}

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot:rw
      - certbot_conf:/etc/letsencrypt/:rw

volumes:
  static_volume:
  certbot_www:
  certbot_conf:

networks:
  backend_{{ cookiecutter.project_slug }}: