[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.format]
# 5. Use single quotes for non-triple-quoted strings.
quote-style = "single"


[tool.pylint.MASTER]
ignore = '.git'
load-plugins = ["pylint_django", "pylint_django.checkers.migrations"]

[tool.pylint."MESSAGES CONTROL"]
disable = '''
pointless-statement,
'''

[tool.pylint.PYLINT_DJANGO]
django-settings-module = "{{ cookiecutter.project_slug }}_service.settings"


[tool.mypy]
mypy_path = "{{ cookiecutter.project_slug }}_service"
python_version = "3.12"
warn_return_any = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "{{ cookiecutter.project_slug }}_service.settings"
strict_settings = false
